name: wolwoloom_widgetbook
description: wloom interactive component gallery (web + mobile).
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  widgetbook: ^3.14.0
  wolwoloom:
    path: ../../packages/wolwoloom

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
